pages:

  only:
  - main  
      
  script:
  # install requirements
  - apt-get update -qy
  - apt-get install -y python3 python3-pip imagemagick
  - pip3 install jinja2 pillow
  # create thumbnails
  - cp -r images thumbnails
  - cd thumbnails 
  - mogrify -resize 100x100 *.jpg
  - cd ../
  # create html 
  - python3 create_html.py
  # prepare deployment
  - mkdir public
  - cp index.html public
  - cp style.css public
  - cp -r images public
  - cp -r thumbnails public
 
  artifacts:
    paths:
    - public
