name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
      - ci

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Generate thumbnails
        run: |
          cp -r images thumbnails
          cd thumbnails
          mogrify -resize 100x100 *.jpg
          cd ..

      - name: Generate html
        run: python3 create_html.py

      - name: Prepare dist folder
        run: |
          mkdir dist
          cp index.html dist 
          cp style.css dist
          cp -r images dist
          cp -r thumbnails dist
              
      - name: Publish generated content to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
