name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
      - ci

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Generate thumbnails
        run: |
          cp -r images thumbnails
          cd thumbnails
          mogrify -resize 100x100 *.jpg
          cd ..

      - name: Generate html
        run: python3 create_html.py

      - name: Prepare dist folder
        run: |
          mkdir dist
          cp index.html dist 
          cp style.css dist
          cp -r images dist
          cp -r thumbnails dist
              
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
